# Generated by Django 4.1 on 2022-08-18 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Educate',
        ),
    ]
